### PR TITLE
Example for Count Sketch

### PR DESCRIPTION
**Pull request by victox5**
Nice package! I thought it could be interesting to give some real case example to be aware of the implications of the different variables.

### CODE REVIEW

**Comment by gakhov** [comment]
Thank you! Please, sync the styling with the existing examples and consider fixing grammatical errors and misspellings.

**Comment by victox5** [comment]
I will check the other examples, thanks.

**Comment by gakhov** [comment]
Take this file as an example https://github.com/gakhov/pdsa/blob/add-examples/examples/frequency/count_min_sketch.py

**Comment by gakhov** [comment]
Closes #24

**Comment by gakhov** [comment]
I see your wish to express 2 cases in the example, for digits and text values. But having two `if __name__ == '__main__':` sections actually very confusing.  

Maybe let's keep the digits only? The case with string is already explained in the [documentation](https://pdsa.readthedocs.io/en/latest/frequency/count_sketch.html) in any case.

**Comment by victox5** [comment]
Cool, we can keep only the numeric example. :)

**Comment by gakhov** [comment]
Thank you and congrats with your first merged PR to PDSA!

**Pull request merged**
